######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 12 15:31:21 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

LIBS += -L/usr/local/lib -lwcl
# Input
HEADERS += Canvas.h GestureIO.h
SOURCES += Canvas.cpp GestureIO.cpp main.cpp
